
name: CI - EP1 Demo

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - run: date
      - run: cat README.md
      - run: echo "Workflow ejecutado correctamente”

name: CI DevOps Basico
on: 
  push:
    branches: [ main, develop ]

jobs:
  job_exitoso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Mensaje de exito
        run: echo "¡La automatización de DevOps funciona perfectamente!"

