name: CI DevOps Basico
on: 
  push:
    branches: [ main, develop ]

jobs:
  job_exitoso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Mensaje de exito
        run: echo "¡La automatización de DevOps funciona perfectamente!"